server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/i/ {
        set $target_host $host;
        if ($http_user_agent ~* "facebookexternalhit|twitterbot|whatsapp|telegrambot|slackbot|discordbot|linkedinbot") {
            set $target_host "api.invtzn.local";
            rewrite ^/i/(.*)$ /api/v1/deployments/og/$1/ break;
            proxy_pass http://invtzn-service-api:8000;
            break;
        }
        
        try_files $uri $uri/ /index.html;
        proxy_set_header Host $target_host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimización: cachea archivos estáticos (js, css, imágenes) por 1 año
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
