# Generated by Django 5.2.17 on 2026-09-21 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0012_remove_deploymentmetric_deployment_delete_systemlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='ID del usuario que reporta/navega', null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('environment', models.CharField(default='sandbox', max_length=50)),
                ('events_payload', models.JSONField(help_text='Payload masivo de eventos DOM de rrweb')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('window_width', models.IntegerField(blank=True, null=True)),
                ('window_height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('USER_ACTION', 'User Action'), ('DEPLOYMENT_STATE', 'Deployment State'), ('PAYMENT_FLOW', 'Payment Flow')], max_length=50)),
                ('message', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('VISIT', 'Visita'), ('RSVP_SUBMIT', 'Confirmación de Asistencia')], default='VISIT', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='Desconocido', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Desconocido', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='deployments.deployment')),
            ],
        ),
    ]
