services:
  invtzn-service-api:
    build: .  # Requiere que tengas tu Dockerfile aquí
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - ../.env
    command: gunicorn invtzn_core.wsgi:application --bind 0.0.0.0:8000
    
    environment:
      - DATABASE_URL=postgres://api_invtzn_user:invtzn-api-password-secure@db_central:5432/api_invtzn_db
    networks:
      - red_publica # Para que el Proxy lo vea
      - red_datos   # Para que pueda hablar con la Base de Datos

networks:
  red_publica:
    external: true
  red_datos:
    external: true