services:
  invtzn-service-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=dev
    restart: unless-stopped
    volumes:
      - .:/app
    command: gunicorn invtzn_core.wsgi:application --bind 0.0.0.0:8000 --no-control-socket
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=invtzn_core.settings.dev
    networks:
      - red_publica
      - red_datos
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - red_datos

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=dev
    restart: unless-stopped
    volumes:
      - .:/app
    command: celery -A invtzn_core worker -l info
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=invtzn_core.settings.dev
    networks:
      - red_datos
    depends_on:
      - redis

networks:
  red_publica:
    external: true
  red_datos:
    external: true