services:
  invtzn-service-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=production
    restart: unless-stopped
    command: gunicorn invtzn_core.wsgi:application --bind 0.0.0.0:8000 --no-control-socket
    env_file:
      - ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=invtzn_core.settings.production
    networks:
      - red_publica
      - red_datos
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M

networks:
  red_publica:
    external: true
  red_datos:
    external: true
