# Generated by Django 5.2.14 on 2026-05-15 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID de la transacción en el banco (STP/BBVA)', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(help_text='Fecha y hora del movimiento bancario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_sync', to='sales.order')),
            ],
        ),
    ]
