# Generated by Django 5.2.14 on 2026-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='Stripe', max_length=50)),
                ('payload', models.JSONField(blank=True, help_text='Cuerpo de la petición recibida', null=True)),
                ('headers', models.JSONField(blank=True, help_text='Cabeceras HTTP recibidas', null=True)),
                ('status', models.CharField(help_text='success, failed, ignored', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
