# Generated by Django 5.2.14 on 2026-05-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vendor_id',
            field=models.IntegerField(blank=True, help_text='ID del vendedor que registró la orden', null=True),
        ),
    ]
