# Generated by Django 5.2.14 on 2026-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_origin_order_store_cashsession_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(default='CARD', help_text='CARD, BANK_TRANSFER, CASH', max_length=50),
        ),
    ]
