# Generated by Django 5.2.14 on 2026-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
