# Generated by Django 5.2.14 on 2026-05-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_order_discount_amount_order_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Correo electrónico para enviar el recibo', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('regimen_fiscal', models.CharField(max_length=3)),
                ('uso_cfdi', models.CharField(max_length=3)),
                ('uuid', models.CharField(help_text='Folio Fiscal SAT (UUID)', max_length=36, unique=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('xml_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.order')),
            ],
        ),
    ]
