# Generated by Django 5.2.14 on 2026-05-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_order_customer_email_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, help_text='Precio cobrado al momento de la compra', max_digits=10),
        ),
    ]
