# Generated by Django 5.2.14 on 2026-05-23 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_order_fulfillment_status_order_is_stock_deducted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: BLACKFRIDAY2026', max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 15.00 para 15%', max_digits=5)),
                ('discount_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Ej: 500.00 para descontar 500 MXN', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=100, help_text='Límite de usos totales')),
                ('current_uses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DirectDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_by', models.IntegerField(help_text='ID del Franquiciatario/Admin que autorizó')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(help_text='Justificación del descuento (Cortesía, Cliente VIP, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_discount', to='sales.order')),
            ],
        ),
    ]
