# Generated by Django 5.2.13 on 2026-05-05 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('DIGITAL', 'Invitación Digital'), ('PHYSICAL', 'Producto Físico (Impresos)'), ('SERVICE', 'Servicio / Boutique')], default='DIGITAL', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_physical', models.BooleanField(default=False)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('has_template', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vue_component_name', models.CharField(help_text="Nombre del componente en el Front (ej: 'ClassicGold')", max_length=100)),
                ('default_config', models.JSONField(default=dict, help_text='Configuración inicial: colores, fuentes, etc.')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_config', to='inventory.product')),
            ],
        ),
    ]
