# Generated by Django 5.2.14 on 2026-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='ID de la cuenta de Stripe Connect', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
