# Generated by Django 5.2.14 on 2026-05-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_store_stripe_account_id_and_more'),
        ('profiles', '0004_alter_userprofile_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Dueño / Franquiciatario de esta sucursal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stores', to='profiles.userprofile'),
        ),
    ]
