# Generated by Django 5.2.14 on 2026-05-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_cost_price_product_min_stock_product_sku_and_more'),
        ('sales', '0008_order_customer_email_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSerialKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_value', models.CharField(max_length=255, unique=True)),
                ('is_assigned', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_keys', to='sales.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_keys', to='inventory.product')),
            ],
        ),
    ]
