# Generated by Django 5.2.14 on 2026-05-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productserialkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Slug único de identificación para la URL', max_length=100, unique=True)),
                ('tier_required', models.CharField(choices=[('BASIC', 'Básico / Gratis'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='BASIC', help_text='Tier mínimo requerido para poder usar este diseño', max_length=20)),
                ('vue_component_name', models.CharField(help_text="Nombre del componente layout en el Frontend (ej: 'ClassicGold')", max_length=100)),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Configuración inicial del diseño: colores, fuentes, etc.')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Miniatura visual para el catálogo de selección', max_length=500, null=True)),
                ('demo_slug', models.CharField(blank=True, help_text='Slug de una invitación demo real para ver este diseño en vivo', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured_on_landing', models.BooleanField(default=False, help_text='Destacar este diseño en la landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de bloques y flags permitidos'),
        ),
        migrations.AddField(
            model_name='product',
            name='tier_level',
            field=models.CharField(choices=[('BASIC', 'Básico / Gratis'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='BASIC', help_text='Nivel comercial de suscripción o tier del producto', max_length=20),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
