# Generated by Django 5.2.14 on 2026-05-26 05:49

from django.db import migrations, models


def set_default_display_pcard(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(id=1).update(display_pcard=True)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_seed_upgrade_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_pcard',
            field=models.BooleanField(default=False, help_text='Define si este producto es el destino por defecto al presionar empezar gratis'),
        ),
        migrations.RunPython(set_default_display_pcard, migrations.RunPython.noop),
    ]
