# Generated by Django 5.2.14 on 2026-05-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_display_pcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='template_slug',
            field=models.CharField(blank=True, help_text='Slug de la invitación base (maqueta) para clonar custom_data', max_length=100, null=True),
        ),
    ]
