# Generated by Django 5.2.14 on 2026-05-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_delete_first_product'),
        ('profiles', '0006_sitereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Creador o diseñador que generó este producto comercial', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Tienda física o sucursal a la que pertenece este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.store'),
        ),
    ]
