# Generated by Django 5.2.13 on 2026-05-05 08:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('remote_auth_id', models.IntegerField(primary_key=True, serialize=False)),
                ('custom_role', models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDOR', 'Vendedor'), ('DESIGNER', 'Diseñador'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_type', models.CharField(choices=[('LEAD', 'Prospecto'), ('ACTIVE', 'Activo'), ('VIP', 'VIP')], default='LEAD', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Notas del CRM para vendedores', null=True)),
                ('base_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje ej. 15.00', max_digits=5)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Saldo a favor del cliente', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('WHATSAPP', 'WhatsApp'), ('VOIP', 'Llamada VoIP'), ('SYSTEM', 'Notificación de Sistema')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WalletLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valores positivos (ingresos) o negativos (cargos)', max_digits=10)),
                ('reason', models.CharField(choices=[('REFUND', 'Reembolso'), ('BANK_DEPOSIT', 'Depósito Bancario'), ('PURCHASE', 'Compra / Cargo')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_logs', to='profiles.userprofile')),
            ],
        ),
    ]
