# Generated by Django 5.2.14 on 2026-05-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nombre completo sincronizado desde api-auth', max_length=255, null=True),
        ),
    ]
