# Generated by Django 5.2.14 on 2026-05-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_store'),
        ('profiles', '0002_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_mode',
            field=models.CharField(choices=[('PHYSICAL', 'En Tienda (Físico)'), ('REMOTE', 'A distancia (Remoto)')], default='REMOTE', max_length=20),
        ),
    ]
