# Generated by Django 5.2.14 on 2026-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_assigned_store_userprofile_vendor_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='custom_role',
            field=models.CharField(choices=[('ADMIN', 'Super Administrador'), ('FRANCHISEE', 'Franquiciatario / Dueño'), ('MANAGER', 'Gerente de Sucursal'), ('VENDOR', 'Vendedor'), ('DESIGNER', 'Diseñador'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=20),
        ),
    ]
