# Generated by Django 5.2.14 on 2026-05-30 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Nombre a mostrar del cliente que escribe la reseña', max_length=150)),
                ('rating', models.IntegerField(default=5, help_text='Calificación de 1 a 5 estrellas')),
                ('comment', models.TextField(help_text='Comentario o testimonio sobre la experiencia con la plataforma')),
                ('is_approved', models.BooleanField(default=False, help_text='Aprobado para mostrarse públicamente en la landing page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.userprofile')),
            ],
        ),
    ]
