# Generated by Django 5.2.14 on 2026-05-13 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='URL única para acceso público', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador / Sandbox'), ('LIVE', 'Publicado'), ('EXPIRED', 'Expirado / Inactivo')], default='DRAFT', max_length=20)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Almacena el diseño de Pinia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
