# Generated by Django 5.2.14 on 2026-05-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='vendor_id',
            field=models.IntegerField(blank=True, help_text='ID del vendedor que registró el diseño', null=True),
        ),
    ]
