# Generated by Django 5.2.14 on 2026-05-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Indica si la invitación ya fue pagada'),
        ),
    ]
