# Generated by Django 5.2.14 on 2026-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deployment_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='user',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del usuario en api-auth', null=True),
        ),
    ]
