# Generated by Django 5.2.14 on 2026-05-16 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_alter_deployment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('VISIT', 'Visita'), ('RSVP_SUBMIT', 'Confirmación de Asistencia')], default='VISIT', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='Desconocido', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Desconocido', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='deployments.deployment')),
            ],
        ),
    ]
