# Generated by Django 5.2.14 on 2026-05-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_deploymentmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='companions_count',
            field=models.IntegerField(default=0, help_text='Número de acompañantes extra'),
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Para enviar el QR por WhatsApp', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='qr_code_token',
            field=models.CharField(blank=True, help_text='Token seguro para generar el QR', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='qr_scanned',
            field=models.BooleanField(default=False, help_text='¿Ya ingresó al salón?'),
        ),
        migrations.AddField(
            model_name='guest',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Aprobación'), ('APPROVED', 'Aprobado (QR Emitido)'), ('DENIED', 'Denegado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='deployments.deployment'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: Boda de Ana y Jorge', max_length=200)),
                ('owner', models.IntegerField(db_index=True, help_text='ID del usuario en api-auth')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployments', models.ManyToManyField(blank=True, related_name='linked_events', to='deployments.deployment')),
            ],
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='deployments.event'),
        ),
    ]
