# Generated by Django 5.2.14 on 2026-05-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_guest_companions_count_guest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('USER_ACTION', 'User Action'), ('DEPLOYMENT_STATE', 'Deployment State'), ('PAYMENT_FLOW', 'Payment Flow')], max_length=50)),
                ('message', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='creation_mode',
            field=models.CharField(choices=[('CATALOG', 'Catalog'), ('CANVAS', 'Canvas')], default='CANVAS', help_text='Modo de creación', max_length=20),
        ),
    ]
