# Generated by Django 5.2.14 on 2026-06-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0009_systemlog_deployment_creation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='dietary_notes',
            field=models.TextField(blank=True, help_text='Alergias o notas de comida', null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='menu_selection',
            field=models.CharField(blank=True, help_text='Menú seleccionado por el invitado', max_length=100, null=True),
        ),
    ]
