# Generated by Django 5.2.14 on 2026-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0010_guest_dietary_notes_guest_menu_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador / Sandbox'), ('ACTIVE', 'Activo (Plantilla)'), ('LIVE', 'Publicado'), ('EXPIRED', 'Expirado / Inactivo')], default='DRAFT', max_length=20),
        ),
    ]
