# Generated by Django 5.2.17 on 2026-09-21 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0011_alter_deployment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentmetric',
            name='deployment',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.DeleteModel(
            name='DeploymentMetric',
        ),
    ]
